



debug: false

#logging:
#  #  pattern:
#   #     console: "%d - %msg%n"
#  #  file:
#   #     path: ./logs/
#   #     name: ./log/my-spring.log
#    #level: com.pop.demo: debug
#    config: classpath:logback-spring-loger.xml

server:
    port: 8080

